---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 3
  source:
    path: kustomize/victoriametrics/
    repoURL: https://github.com/DuraCHYo/k3s-infra.git
    targetRevision: master
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

